In [1]:
import os
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 1. PyTorch Basics

## 1.1 Define Torch Objects

In [4]:
# Scalar
scalar = torch.tensor(10)
print(type(scalar))

<class 'torch.Tensor'>


In [6]:
# Vector
vector = torch.tensor([1,2,3,4,5])
print(type(vector))
print(vector.ndim)

<class 'torch.Tensor'>
1


In [8]:
# Matrix
matrix = torch.tensor([[1,2],
                       [3,4],
                       [4,5]])
print(type(matrix))
print(matrix.ndim)

<class 'torch.Tensor'>
2


In [11]:
# Random Tensor
random_tensor = torch.rand(size=(3,3))
random_tensor

tensor([[0.0638, 0.2747, 0.4787],
        [0.0898, 0.2051, 0.3363],
        [0.2329, 0.9900, 0.9017]])

In [13]:
# Zero Tensor
zero_tensor = torch.zeros(size=(3,3))
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [14]:
# Zero Tensor
ones_tensor = torch.ones(size=(3,3))
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [15]:
# Multiply Tensors
random_tensor * ones_tensor

tensor([[0.0638, 0.2747, 0.4787],
        [0.0898, 0.2051, 0.3363],
        [0.2329, 0.9900, 0.9017]])

In [22]:
# Range of numbers
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
# Creating tensors like
ten_ones = torch.ones_like(one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## 1.2 Torch Datatypes

In [26]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # Define datatype of the tensor
                               device=None, # The tensor is not put to GPU in this example
                               requires_grad=False) # Doesn't track gradient for this tensor's operation
print(float_32_tensor)
print(float_32_tensor.dtype)

tensor([3., 6., 9.])
torch.float32


In [27]:
# Float 16 tensor
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,
                               device=None, 
                               requires_grad=False)
print(float_16_tensor)
print(float_16_tensor.dtype)

tensor([3., 6., 9.], dtype=torch.float16)
torch.float16
